name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dotnet build
      run: dotnet build --configuration Release

    - name: Dotnet test
      run: dotnet test

    - name: Typescript install
      run: npm ci
      working-directory: ./DotnetTemplate.Web

    - name: Typescript build
      run: npm run build 
      working-directory: ./DotnetTemplate.Web

    - name: Typescript test
      run: npm run test
      working-directory: ./DotnetTemplate.Web
  dockerhub:
    name: Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Docker Build
      run: docker build -t rubydoma/module-8 .

    - name: Login
      run: echo ${{secrets.DOCKERHUBTOKEN}} | docker login --username rubydoma --password-stdin
      
    - name: Push
      run: docker push rubydoma/module-8

  heroku:
    runs-on: ubuntu-latest
    needs: dockerhub
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKUAPI}}
          heroku_app_name: "module8-corndel" #Must be unique in Heroku
          heroku_email: "ruby.domanico@kpmg.co.uk"
          usedocker: true

